#!/bin/bash

# Create Images directory if it doesn't exist
mkdir -p Images

# Download wallet logos
echo "Downloading wallet logos..."

# Popular wallets
curl -L -o "Images/metamask.png" "https://metamask.io/images/metamask-fox.svg" 2>/dev/null && echo "✓ MetaMask" || echo "✗ MetaMask"
curl -L -o "Images/trustwallet.png" "https://trustwallet.com/assets/images/media/assets/logo.png" 2>/dev/null && echo "✓ Trust Wallet" || echo "✗ Trust Wallet"
curl -L -o "Images/phantom.png" "https://phantom.app/img/logo.png" 2>/dev/null && echo "✓ Phantom" || echo "✗ Phantom"
curl -L -o "Images/coinbase.png" "https://www.coinbase.com/favicon.ico" 2>/dev/null && echo "✓ Coinbase" || echo "✗ Coinbase"
curl -L -o "Images/ledger.png" "https://www.ledger.com/favicon.ico" 2>/dev/null && echo "✓ Ledger" || echo "✗ Ledger"
curl -L -o "Images/cryptocom.png" "https://crypto.com/favicon.ico" 2>/dev/null && echo "✓ Crypto.com" || echo "✗ Crypto.com"
curl -L -o "Images/argent.png" "https://www.argent.xyz/favicon.ico" 2>/dev/null && echo "✓ Argent" || echo "✗ Argent"
curl -L -o "Images/solflare.png" "https://solflare.com/favicon.ico" 2>/dev/null && echo "✓ Solflare" || echo "✗ Solflare"
curl -L -o "Images/tonkeeper.png" "https://tonkeeper.com/favicon.ico" 2>/dev/null && echo "✓ Tonkeeper" || echo "✗ Tonkeeper"
curl -L -o "Images/okx.png" "https://www.okx.com/favicon.ico" 2>/dev/null && echo "✓ OKX" || echo "✗ OKX"
curl -L -o "Images/keplr.png" "https://www.keplr.app/favicon.ico" 2>/dev/null && echo "✓ Keplr" || echo "✗ Keplr"
curl -L -o "Images/zengo.png" "https://zengo.com/favicon.ico" 2>/dev/null && echo "✓ Zengo" || echo "✗ Zengo"
curl -L -o "Images/trezor.png" "https://trezor.io/favicon.ico" 2>/dev/null && echo "✓ Trezor" || echo "✗ Trezor"
curl -L -o "Images/solana.png" "https://solana.com/favicon.ico" 2>/dev/null && echo "✓ Solana" || echo "✗ Solana"
curl -L -o "Images/blockchain.png" "https://www.blockchain.com/favicon.ico" 2>/dev/null && echo "✓ Blockchain" || echo "✗ Blockchain"
curl -L -o "Images/bitpay.png" "https://bitpay.com/favicon.ico" 2>/dev/null && echo "✓ BitPay" || echo "✗ BitPay"
curl -L -o "Images/tokenpocket.png" "https://www.tokenpocket.pro/favicon.ico" 2>/dev/null && echo "✓ TokenPocket" || echo "✗ TokenPocket"
curl -L -o "Images/imtoken.png" "https://token.im/favicon.ico" 2>/dev/null && echo "✓ imToken" || echo "✗ imToken"
curl -L -o "Images/pillar.png" "https://www.pillar.fi/favicon.ico" 2>/dev/null && echo "✓ Pillar" || echo "✗ Pillar"
curl -L -o "Images/rainbow.png" "https://rainbow.me/favicon.ico" 2>/dev/null && echo "✓ Rainbow" || echo "✗ Rainbow"
curl -L -o "Images/mathwallet.png" "https://mathwallet.org/favicon.ico" 2>/dev/null && echo "✓ MathWallet" || echo "✗ MathWallet"
curl -L -o "Images/onto.png" "https://onto.app/favicon.ico" 2>/dev/null && echo "✓ Onto" || echo "✗ Onto"
curl -L -o "Images/authereum.png" "https://authereum.org/favicon.ico" 2>/dev/null && echo "✓ Authereum" || echo "✗ Authereum"
curl -L -o "Images/walleth.png" "https://walleth.org/favicon.ico" 2>/dev/null && echo "✓ Walleth" || echo "✗ Walleth"
curl -L -o "Images/oneinch.png" "https://1inch.io/favicon.ico" 2>/dev/null && echo "✓ 1inch" || echo "✗ 1inch"
curl -L -o "Images/trustvault.png" "https://www.onespan.com/favicon.ico" 2>/dev/null && echo "✓ TrustVault" || echo "✗ TrustVault"
curl -L -o "Images/atomic.png" "https://atomicwallet.io/favicon.ico" 2>/dev/null && echo "✓ Atomic" || echo "✗ Atomic"
curl -L -o "Images/coin98.png" "https://coin98.com/favicon.ico" 2>/dev/null && echo "✓ Coin98" || echo "✗ Coin98"
curl -L -o "Images/coolwallet.png" "https://www.coolwallet.io/favicon.ico" 2>/dev/null && echo "✓ CoolWallet" || echo "✗ CoolWallet"
curl -L -o "Images/loopring.png" "https://loopring.io/favicon.ico" 2>/dev/null && echo "✓ Loopring" || echo "✗ Loopring"
curl -L -o "Images/alphawallet.png" "https://alphawallet.com/favicon.ico" 2>/dev/null && echo "✓ AlphaWallet" || echo "✗ AlphaWallet"
curl -L -o "Images/safepal.png" "https://www.safepal.com/favicon.ico" 2>/dev/null && echo "✓ SafePal" || echo "✗ SafePal"
curl -L -o "Images/dcent.png" "https://dcentwallet.com/favicon.ico" 2>/dev/null && echo "✓ D'CENT" || echo "✗ D'CENT"
curl -L -o "Images/zelcore.png" "https://runonflux.io/favicon.ico" 2>/dev/null && echo "✓ Zelcore" || echo "✗ Zelcore"
curl -L -o "Images/nash.png" "https://nash.io/favicon.ico" 2>/dev/null && echo "✓ Nash" || echo "✗ Nash"
curl -L -o "Images/coinomi.png" "https://www.coinomi.com/favicon.ico" 2>/dev/null && echo "✓ Coinomi" || echo "✗ Coinomi"
curl -L -o "Images/gridplus.png" "https://gridplus.io/favicon.ico" 2>/dev/null && echo "✓ GridPlus" || echo "✗ GridPlus"
curl -L -o "Images/cybavo.png" "https://www.cybavo.com/favicon.ico" 2>/dev/null && echo "✓ CYBAVO" || echo "✗ CYBAVO"
curl -L -o "Images/tokenary.png" "https://tokenary.io/favicon.ico" 2>/dev/null && echo "✓ Tokenary" || echo "✗ Tokenary"
curl -L -o "Images/torus.png" "https://tor.us/favicon.ico" 2>/dev/null && echo "✓ Torus" || echo "✗ Torus"
curl -L -o "Images/spatium.png" "https://spatium.net/favicon.ico" 2>/dev/null && echo "✓ Spatium" || echo "✗ Spatium"
curl -L -o "Images/walletio.png" "https://wallet.io/favicon.ico" 2>/dev/null && echo "✓ wallet.io" || echo "✗ wallet.io"
curl -L -o "Images/infinitywallet.png" "https://infinitywallet.io/favicon.ico" 2>/dev/null && echo "✓ Infinity Wallet" || echo "✗ Infinity Wallet"
curl -L -o "Images/easypocket.png" "https://easycrypto.com/favicon.ico" 2>/dev/null && echo "✓ EasyPocket" || echo "✗ EasyPocket"
curl -L -o "Images/sparkpoint.png" "https://sparkpoint.io/favicon.ico" 2>/dev/null && echo "✓ SparkPoint" || echo "✗ SparkPoint"
curl -L -o "Images/binancesmartchain.png" "https://www.bnbchain.org/favicon.ico" 2>/dev/null && echo "✓ Binance Smart Chain" || echo "✗ Binance Smart Chain"
curl -L -o "Images/morix.png" "https://morixjp.com/favicon.ico" 2>/dev/null && echo "✓ MoriX" || echo "✗ MoriX"
curl -L -o "Images/trustee.png" "https://trusteeglobal.com/favicon.ico" 2>/dev/null && echo "✓ Trustee" || echo "✗ Trustee"
curl -L -o "Images/bitget.png" "https://www.bitget.site/favicon.ico" 2>/dev/null && echo "✓ BitGet" || echo "✗ BitGet"
curl -L -o "Images/leapwallet.png" "https://www.leapwallet.io/favicon.ico" 2>/dev/null && echo "✓ Leap Wallet" || echo "✗ Leap Wallet"

echo "Logo download complete!" 
